package DemoApp;


/**
* DemoApp/DemoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from demo.idl
* Monday, October 27, 2014 3:55:44 PM EST
*/

abstract public class DemoHelper
{
  private static String  _id = "IDL:DemoApp/Demo:1.0";

  public static void insert (org.omg.CORBA.Any a, DemoApp.Demo that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DemoApp.Demo extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (DemoApp.DemoHelper.id (), "Demo");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DemoApp.Demo read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DemoStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DemoApp.Demo value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static DemoApp.Demo narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DemoApp.Demo)
      return (DemoApp.Demo)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DemoApp._DemoStub stub = new DemoApp._DemoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static DemoApp.Demo unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DemoApp.Demo)
      return (DemoApp.Demo)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DemoApp._DemoStub stub = new DemoApp._DemoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
