/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2017-10-31 02:18:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registerForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction registerData() {\r\n");
      out.write("\t\tvar f = document.registerForm; \r\n");
      out.write("\t\tif(f.id.value==\"\"){\r\n");
      out.write("\t\t\talert(\"아이디를 입력하세여\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}if(f.password.value==\"\"){\r\n");
      out.write("\t\t\talert(\"패스워드를 입력하세여\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}if(f.name.value==\"\"){\r\n");
      out.write("\t\t\talert(\"이름을 입력하세여\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}if(f.address.value==\"\"){\r\n");
      out.write("\t\t\talert(\"주소를 입력하세여\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(checkFlag==false){\r\n");
      out.write("\t\t\talert(\"아이디 중복 확인부터 하세여\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}//registerData\t\r\n");
      out.write("\tvar xhr;\r\n");
      out.write("\tfunction checkId() {\r\n");
      out.write("\t\txhr = new XMLHttpRequest();\r\n");
      out.write("\t\tvar id = document.getElementById(\"memberId\").value;\r\n");
      out.write("\t\txhr.onreadystatechange = callback;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\txhr.open(\"post\", \"DispatcherServlet\", true);\r\n");
      out.write("\t\txhr.setRequestHeader(\"Content-Type\",\"application/x-www-form-urlencoded;charset=utf-8\");\r\n");
      out.write("\t\txhr.send(\"command=idCheck&&id=\"+id);\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction callback() {\r\n");
      out.write("\t\tif(xhr.readyState == 4) {\r\n");
      out.write("\t\t\tif(xhr.status == 200) {\r\n");
      out.write("\t\t\t\tvar flag = xhr.responseText;\r\n");
      out.write("\t\t\t\tvar checkResult = document.getElementById(\"checkResult\");\r\n");
      out.write("\t\t\t\tif(flag==\"true\") {\r\n");
      out.write("\t\t\t\t\tcheckResult.innerHTML = \"<font color='red'>NOT USABLE</font>\";\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tcheckResult.innerHTML = \"<font color='blue'>USABLE</font>\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h2 align=\"center\">Member Register Form...</h2><p>\r\n");
      out.write("<form action=\"DispatcherServlet\" method=\"post\" name=\"registerForm\" onsubmit=\"return registerData()\">\r\n");
      out.write("아이디 : <input type=\"text\" name=\"id\" id=\"memberId\">\r\n");
      out.write("<input type=\"button\" value=\"중복확인\" onclick=\"checkId()\">\r\n");
      out.write("<span id=\"checkResult\"></span><br><br>\r\n");
      out.write("패스워드 : <input type=\"password\" name=\"password\"><br><br>\r\n");
      out.write("이름 : <input type=\"text\" name=\"name\" ><br><br>\r\n");
      out.write("주소 : <input type=\"text\" name=\"address\" ><br><br>\r\n");
      out.write("<input type=\"submit\" value=\"회원등록\">\r\n");
      out.write("<input type=\"hidden\" name=\"command\" value=\"register\">\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
