/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2017-09-26 03:07:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vo.Student;
import java.util.ArrayList;

public final class editProfile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <title>KOStudent</title>\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, width=device-width\">\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"/>\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n");
      out.write("  <link href=\"./css/home.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("  <link rel=\"shortcut icon\" type=\"image/png\" href=\"./image/favicon.png\"/>\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js\"></script>\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"./js/chattingScript.js\"></script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<img src=\"./image/background_image.png\" id=\"bg\" alt=\"\">\n");
      out.write("<!-- For Navigation Bar ... -->\n");
      out.write("  <nav class=\"navbar navbar-inverse navbar-fixed-top\">\n");
      out.write("      <div class=\"container-fluid\">\n");
      out.write("        <div class=\"navbar-header\">\n");
      out.write("          <a class=\"navbar-brand\" href=\"splash.html\">KOStudent</a>\n");
      out.write("        </div>\n");
      out.write("        <ul class=\"nav navbar-nav\">\n");
      out.write("          <li><a href=\"index.html\">Home</a></li>\n");
      out.write("          <li><a href=\"notice.html\">Notice</a></li>\n");
      out.write("          <li><a href=\"#\">Discussion</a></li>\n");
      out.write("          <li><a href=\"#\">Contact Us</a></li>\n");
      out.write("        </ul>\n");
      out.write("        <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("        <li><a href=\"login_check.jsp\"><span class=\"glyphicon glyphicon-user\"></span> Cancel</a></li>\n");
      out.write("\n");
      out.write("       </ul>\n");
      out.write("      </div>\n");
      out.write("  </nav>\n");
      out.write("<!-- For Navigation Bar ... -->\n");
 
	ArrayList<Student> list = (ArrayList<Student>)application.getAttribute("studentDB");
	Student currentUser = (Student)application.getAttribute("user");
	

      out.write("\n");
      out.write("\n");
      out.write("<div class=\"container\" style=\"margin-top:100px\">\n");
      out.write("  <div class=\"jumbotron\" width=\"30%\">\n");
      out.write("    <h1>Edit Profile</h1> <hr>\n");
      out.write("    \n");
      out.write("    <!-- ID INPUT -->\n");
      out.write("   \t<p>\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("      <label for=\"disabledInput\" class=\"col-sm-2 control-label\">ID</label>\n");
      out.write("      <div class=\"col-sm-10\">\n");
      out.write("        <input class=\"form-control\" id=\"disabledInput\" type=\"text\" placeholder=");
      out.print( currentUser.getName() );
      out.write(" disabled>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <!--  -<fieldset disabled></p> -->\n");
      out.write("    \n");
      out.write("    <!-- Password INPUT -->\n");
      out.write("    <!-- Previous Password -->\n");
      out.write("\t<div class=\"form-group\">\n");
      out.write("\t  <label for=\"pwd\">Current Password:</label> <input type=\"password\" class=\"form-control\" id=\"pwd\" >\n");
      out.write("\t</div>\n");
      out.write("\t    \n");
      out.write("    \n");
      out.write("    <p>Contact me on : +82-10-2616-6795<br>@Kakao : Jasonchoi93</p>\n");
      out.write("\n");
      out.write(" \n");
      out.write("  </div>\n");
      out.write("</div>\n");
      out.write("  \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
