/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2017-09-26 00:31:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vo.Student;

public final class login_005fcheck_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <title>KOStudent</title>\n");
      out.write("  <meta name=\"viewport\" content=\"user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, width=device-width\">\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"/>\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n");
      out.write("  <link href=\"./css/home.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js\"></script>\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"./js/chattingScript.js\"></script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<img src=\"./image/background_image.png\" id=\"bg\" alt=\"\">\n");
      out.write("<!-- For Navigation Bar ... -->\n");
      out.write("  <nav class=\"navbar navbar-inverse navbar-fixed-top\">\n");
      out.write("      <div class=\"container-fluid\">\n");
      out.write("        <div class=\"navbar-header\">\n");
      out.write("          <a class=\"navbar-brand\" href=\"splash.html\">KOStudent</a>\n");
      out.write("        </div>\n");
      out.write("        <ul class=\"nav navbar-nav\">\n");
      out.write("          <li class=\"active\"><a href=\"index.html\">Home</a></li>\n");
      out.write("          <li><a href=\"notice.html\">Notice</a></li>\n");
      out.write("          <li><a href=\"#\">Discussion</a></li>\n");
      out.write("          <li><a href=\"#\">Contact Us</a></li>\n");
      out.write("        </ul>\n");
      out.write("        <ul class=\"nav navbar-nav navbar-right\">\n");
 
		if( session.getAttribute("login_result").equals(Student.LOGIN_SUCCESS + " ")) { 
      out.write("\n");
      out.write("\t     \t<li><a href=\"LogOut\" ><span class=\"glyphicon glyphicon-log-in\"></span> Log Out</a></li>");


		} else { 
      out.write("\n");
      out.write("\t\t    <li><a href=\"#\" data-toggle=\"modal\" data-target=\"#modal_SignUP\"><span class=\"glyphicon glyphicon-user\"></span> Sign Up</a></li>\n");
      out.write("     \t\t<li><a href=\"#\" data-toggle=\"modal\" data-target=\"#modal_SignIn\"><span class=\"glyphicon glyphicon-log-in\"></span> Login</a></li>\n");
      out.write("\t\t\t");
 //request.getRequestDispatcher("index.html").forward(request, response); 
	    }

      out.write("\n");
      out.write("        \n");
      out.write("       </ul>\n");
      out.write("      </div>\n");
      out.write("  </nav>\n");
      out.write("<!-- For Navigation Bar ... -->\n");
      out.write("\n");
      out.write("<div class=\"container\" style=\"margin-top:100px\">\n");
      out.write("  <div class=\"jumbotron\">\n");
      out.write("    <h1>KOStudent</h1> <hr>\n");
      out.write("    <p>This is a community web-site for students @KOSTA.</p> \n");
      out.write("    <p>Contact me on : +82-10-2616-6795<br>@Kakao : Jasonchoi93</p>\n");
      out.write("    <p><a href=\"#\" data-toggle=\"collapse\" data-target=\"#meal\">오늘의 식단(미래에셋)</a></p> \n");
      out.write("    <div id=\"meal\" class=\"collapse\">\n");
      out.write("      <img src=\"./image/meal_1.jpeg\">\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    \n");
      out.write("  </div>\n");
      out.write("  <div class=\"jumbotron\">\n");
      out.write("    <h1>My Class    \n");
      out.write("      <a href=\"#\" id=\"refresh_class\">\n");
      out.write("            <span class=\"glyphicon glyphicon-refresh\"></span>\n");
      out.write("      </a> \n");
      out.write("    </h1>\n");
      out.write("    <h2>수료일 (2017.12.29)</h2>\n");
      out.write("    \n");
      out.write("    <div class=\"progress\">\n");
      out.write("\t\t<div class=\"progress-bar\" role=\"progressbar\" aria-valuenow=\"20\" \n");
      out.write("\t\t\taria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width:20%\">\n");
      out.write("\t    20%\n");
      out.write("  \t\t</div>\n");
      out.write("\t</div>\n");
      out.write("    <hr>\n");
      out.write("    <!-- Messages go top-down way thread -->\n");
      out.write("    <div class=\"msgs\" id=\"myClass\">\n");
      out.write("<!-- Temp. Messages -->\n");
      out.write("\t    <!-- Left-aligned -->\n");
      out.write("\t\t<div class=\"media\">\n");
      out.write("\t\t  <div class=\"media-left\">\n");
      out.write("\t\t    <img src=\"./image/img_avatar1.png\" class=\"media-object\" style=\"width:60px\">\n");
      out.write("\t\t  </div>\n");
      out.write("\t\t  <div class=\"media-body\">\n");
      out.write("\t\t    <h4 class=\"media-heading\">(174) 최수영</h4>\n");
      out.write("\t\t    <p>저 내일 못와요... (17.09.18)</p>\n");
      out.write("\t\t  </div>\n");
      out.write("\t\t</div>\n");
      out.write("    \n");
      out.write("        <!-- Left-aligned -->\n");
      out.write("\t\t<div class=\"media\">\n");
      out.write("\t\t  <div class=\"media-left\">\n");
      out.write("\t\t    <img src=\"./image/img_avatar2.png\" class=\"media-object\" style=\"width:60px\">\n");
      out.write("\t\t  </div>\n");
      out.write("\t\t  <div class=\"media-body\">\n");
      out.write("\t\t    <h4 class=\"media-heading\">(174) 김인수</h4>\n");
      out.write("\t\t    <p>네 말씀드리겠습니다~ (17.09.18)</p>\n");
      out.write("\t\t  </div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t    <!-- Left-aligned -->\n");
      out.write("\t\t<div class=\"media\">\n");
      out.write("\t\t  <div class=\"media-left\">\n");
      out.write("\t\t    <img src=\"./image/img_avatar2.png\" class=\"media-object\" style=\"width:60px\">\n");
      out.write("\t\t  </div>\n");
      out.write("\t\t  <div class=\"media-body\">\n");
      out.write("\t\t    <h4 class=\"media-heading\">(174) 김인수</h4>\n");
      out.write("\t\t    <p><b><font color='red'>공지</font></b> 오늘 회식 있습니다 ^^ <a href=\"#\" data-toggle=\"modal\" data-target=\"#tempModal\">#치어스</a> (17.09.22) </p>\n");
      out.write("\t\t  </div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- Temp. Messages -->\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("    <br><br><p>Message : <input type=\"text\" id=\"inputMsg_1\">\n");
      out.write("    <button type=\"button\" class=\"btn btn-primary\" id=\"sendMsg_1\">Send</button>\n");
      out.write("\t<select>\n");
      out.write("\t\t<option>일반</option>\n");
      out.write("\t\t<option>공지</option>\n");
      out.write("\t\t<option>투표</option>\n");
      out.write("\t</select>\n");
      out.write("    </p>\n");
      out.write("\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <div class=\"jumbotron\">\n");
      out.write("    <h1>All Classes</h1> \n");
      out.write("\n");
      out.write("    <div clas=\"msgs\" id=\"allClass\">\n");
      out.write("\t    <p>(174) 최수영 : 청소기 미리 예약점; (17.09.18)</p>\n");
      out.write("\t    <p>(172) 아무개 : ㄴㄴ (17.09.18)</p> \n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\t<br><br><p>Message : <input type=\"text\" id=\"inputMsg_2\"> \n");
      out.write("\t<button type=\"button\" class=\"btn btn-primary\" id=\"sendMsg_2\">Send</button></p>\n");
      out.write("\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("    <div class=\"jumbotron\">\n");
      out.write("    <h1>Live Thread</h1> \n");
      out.write("    <p><a href=\"#\" data-toggle=\"collapse\" data-target=\"#temp_1\">174기 회식 (17.09.22) @치어스</a></p> \n");
      out.write("   \t<div id=\"temp_1\" class=\"collapse\">\n");
      out.write("      <img src=\"./image/cheers.png\">\n");
      out.write("    </div>\n");
      out.write("    <p><a href=\"#\" data-toggle=\"collapse\" data-target=\"#temp_2\">166기 수료 (17.09.22)</a></p> \n");
      out.write("    <div id=\"temp_2\" class=\"collapse\">\n");
      out.write("      축하합니다 ^^\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("<div id=\"footer\" align=\"center\"><b>KOStudent by Jason Choi.</b></div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- Modal for Sign-up -->\n");
      out.write("<div class=\"modal fade\" id=\"modal_SignUP\" role=\"dialog\">\n");
      out.write("  <div class=\"modal-dialog\">\n");
      out.write("    <!-- Modal content-->\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("      <div class=\"modal-header\">\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("        <h4 class=\"modal-title\">Log-In Anonymously</h4>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-body\">\n");
      out.write("\t\t<form action=\"SC_SignUp\" method=\"get\" id=\"frm_signup\">\n");
      out.write("\t\t\tClass : \n");
      out.write("\t\t\t<select name=\"userClass\" id=\"selectClass_signup\" class=\"s\">\n");
      out.write("\t\t\t\t<option value=\"174\">174</option>\n");
      out.write("\t\t\t\t<option value=\"173\">173</option>\n");
      out.write("\t\t\t\t<option value=\"172\">172</option>\n");
      out.write("\t\t\t</select>\n");
      out.write("\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t  <label for=\"usr\">Name:</label>\n");
      out.write("\t\t\t  <input type=\"text\" class=\"form-control\" name=\"usr\" required=\"required\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"form-group\">\n");
      out.write("\t   \t\t\t<label for=\"pwd\">Password:</label>\n");
      out.write("\t   \t\t\t<input type=\"password\" class=\"form-control\" name=\"pwd\" required=\"required\">\n");
      out.write("\t  \t\t</div>\n");
      out.write("\t\t  <div class=\"checkbox\">\n");
      out.write("\t\t    <label><input type=\"checkbox\"> Remember me</label>\n");
      out.write("\t\t  </div>\n");
      out.write("\t\t  <button type=\"submit\" class=\"btn btn-default\">Submit</button>\n");
      out.write("\t\t</form>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div> \n");
      out.write("<!-- Modal -->\n");
      out.write("\n");
      out.write("<!-- Modal for Sign-in -->\n");
      out.write("<div class=\"modal fade\" id=\"modal_SignIn\" role=\"dialog\">\n");
      out.write("  <div class=\"modal-dialog\">\n");
      out.write("    <!-- Modal content-->\n");
      out.write("    <div class=\"modal-content\">\n");
      out.write("      <div class=\"modal-header\">\n");
      out.write("        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("        <h4 class=\"modal-title\">Log-In Anonymously</h4>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal-body\">\n");
      out.write("\t\t<form action=\"SC_Login\" method=\"get\" id=\"frm\">\n");
      out.write("\t\t\tClass : \n");
      out.write("\t\t\t<select name=\"userClass\" id=\"selectClass\" class=\"s\">\n");
      out.write("\t\t\t\t<option value=\"174\">174</option>\n");
      out.write("\t\t\t\t<option value=\"173\">173</option>\n");
      out.write("\t\t\t\t<option value=\"172\">172</option>\n");
      out.write("\t\t\t</select>\n");
      out.write("\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t  <label for=\"usr\">Name:</label>\n");
      out.write("\t\t\t  <input type=\"text\" class=\"form-control\" name=\"usr\" required=\"required\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"form-group\">\n");
      out.write("\t   \t\t\t<label for=\"pwd\">Password:</label>\n");
      out.write("\t   \t\t\t<input type=\"password\" class=\"form-control\" name=\"pwd\" required=\"required\">\n");
      out.write("\t  \t\t</div>\n");
      out.write("\t\t  <div class=\"checkbox\">\n");
      out.write("\t\t    <label><input type=\"checkbox\"> Remember me</label>\n");
      out.write("\t\t  </div>\n");
      out.write("\t\t  <button type=\"submit\" class=\"btn btn-default\">Submit</button>\n");
      out.write("\t\t</form>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</div> \n");
      out.write("<!-- Modal -->\n");
      out.write("\n");
      out.write(" <!-- tempModal (Advertisement) -->\n");
      out.write("  <div class=\"modal fade\" id=\"tempModal\" role=\"dialog\">\n");
      out.write("    <div class=\"modal-dialog modal-lg\">\n");
      out.write("    \n");
      out.write("      <!-- Modal content-->\n");
      out.write("      <div class=\"modal-content\">\n");
      out.write("        <div class=\"modal-header\">\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("          <h4 class=\"modal-title\">치어스</h4>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"modal-body\">\n");
      out.write("          <p>치어스 : 경기 성남시 분당구 대왕판교로 660 3층</p>\n");
      out.write("          \n");
      out.write("\t\t\t<div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\">\n");
      out.write("\t\t\t  <!-- Indicators -->\n");
      out.write("\t\t\t  <ol class=\"carousel-indicators\">\n");
      out.write("\t\t\t    <li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\n");
      out.write("\t\t\t    <li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\n");
      out.write("\t\t\t    <li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\n");
      out.write("\t\t\t  </ol>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t  <!-- Wrapper for slides -->\n");
      out.write("\t\t\t  <div class=\"carousel-inner\">\n");
      out.write("\t\t\t    <div class=\"item active\">\n");
      out.write("\t\t\t      <img src=\"./image/adv/1.jpg\" alt=\"Los Angeles\" width=240px height=240px>\n");
      out.write("\t\t\t    </div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t    <div class=\"item\">\n");
      out.write("\t\t\t      <img src=\"./image/adv/2.jpg\" alt=\"Chicago\" width=240px height=240px>\n");
      out.write("\t\t\t    </div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t    <div class=\"item\">\n");
      out.write("\t\t\t      <img src=\"./image/adv/3.jpg\" alt=\"New York\" width=240px height=240px>\n");
      out.write("\t\t\t    </div>\n");
      out.write("\t\t\t  </div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t  <!-- Left and right controls -->\n");
      out.write("\t\t\t  <a class=\"left carousel-control\" href=\"#myCarousel\" data-slide=\"prev\">\n");
      out.write("\t\t\t    <span class=\"glyphicon glyphicon-chevron-left\"></span>\n");
      out.write("\t\t\t    <span class=\"sr-only\">Previous</span>\n");
      out.write("\t\t\t  </a>\n");
      out.write("\t\t\t  <a class=\"right carousel-control\" href=\"#myCarousel\" data-slide=\"next\">\n");
      out.write("\t\t\t    <span class=\"glyphicon glyphicon-chevron-right\"></span>\n");
      out.write("\t\t\t    <span class=\"sr-only\">Next</span>\n");
      out.write("\t\t\t  </a>\n");
      out.write("\t\t\t</div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"modal-footer\">\n");
      out.write("          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      \n");
      out.write("    </div>\n");
      out.write("  </div> \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
