package DemoApp;

/**
* DemoApp/DemoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from demo.idl
* Monday, October 27, 2014 3:55:44 PM EST
*/

public final class DemoHolder implements org.omg.CORBA.portable.Streamable
{
  public DemoApp.Demo value = null;

  public DemoHolder ()
  {
  }

  public DemoHolder (DemoApp.Demo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DemoApp.DemoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DemoApp.DemoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DemoApp.DemoHelper.type ();
  }

}
