package DemoApp;


/**
* DemoApp/Demo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from demo.idl
* Monday, October 27, 2014 3:55:44 PM EST
*/

public interface Demo extends DemoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Demo
