package DemoApp;


/**
* DemoApp/DemoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from demo.idl
* Monday, October 27, 2014 3:55:44 PM EST
*/

public interface DemoOperations 
{
  char randomChar ();
  void shutdown ();
} // interface DemoOperations
